# Generated by Django 4.2.27 on 2026-03-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_instrumentcategory_instrumentsubcategory_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
