# Generated by Django 4.2.29 on 2026-03-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_instrument_material_instrument_note_instrument_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='instruments/')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.instrument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
