"""
Django settings for SingingBallAndGongHouse project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
import logging
from django.core.exceptions import ImproperlyConfigured

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # python-dotenv not installed, continue without it
    pass

# Set up logger for settings
logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Helper functions for environment variables
def get_env_bool(name: str, default: bool = False) -> bool:
    """Get boolean from environment variable."""
    value = os.getenv(name, str(default)).strip().lower()
    return value in ("1", "true", "yes", "on")


def get_env_list(name: str, default: str = "") -> list:
    """Get comma-separated list from environment variable."""
    raw = os.getenv(name, default).strip()
    if not raw:
        return []
    return [item.strip() for item in raw.split(",") if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "").strip()

if not SECRET_KEY:
    if get_env_bool("DEBUG", True):
        # Development-only fallback
        SECRET_KEY = "django-insecure-development-only-change-me-in-production"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG=False."
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool("DEBUG", False)

# Hosts (comma-separated): ALLOWED_HOSTS=example.com,www.example.com
ALLOWED_HOSTS = get_env_list("ALLOWED_HOSTS")

# Auto-allow Render external hostname if present
render_hostname = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_hostname:
    if render_hostname not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(render_hostname)

# Default allowed hosts for development
if not ALLOWED_HOSTS and DEBUG:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# Production check
if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured(
        "ALLOWED_HOSTS environment variable is required when DEBUG=False."
    )


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",  # Main app
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SingingBallAndGongHouse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "main" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "SingingBallAndGongHouse.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = os.getenv("TIME_ZONE", "Asia/Kathmandu").strip()

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "main" / "static"]

# WhiteNoise configuration for static files
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# WhiteNoise additional settings
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = DEBUG


# Media files (User uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# --------------------------------------------------
# Email Configuration (Gmail SMTP)
# --------------------------------------------------
# Required environment variables:
#   EMAIL_HOST_USER: Gmail address
#   EMAIL_HOST_PASSWORD: Gmail App Password (not regular password)
#   DEFAULT_FROM_EMAIL: Sender email address
#   BOOKING_RECEIVER_EMAIL: Email to receive booking notifications
#
# Optional:
#   ADMIN_EMAIL: Admin email (defaults to BOOKING_RECEIVER_EMAIL)

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "").strip()
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "").strip()
BOOKING_RECEIVER_EMAIL = os.getenv("BOOKING_RECEIVER_EMAIL", "").strip()
ADMIN_EMAIL = os.getenv(
    "ADMIN_EMAIL",
    BOOKING_RECEIVER_EMAIL or DEFAULT_FROM_EMAIL
).strip()

SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Validation
if not EMAIL_HOST_USER:
    logger.warning("EMAIL_HOST_USER not set. Email sending may fail.")
if not EMAIL_HOST_PASSWORD:
    logger.warning("EMAIL_HOST_PASSWORD not set. Email sending may fail.")
if not DEFAULT_FROM_EMAIL:
    raise ImproperlyConfigured("DEFAULT_FROM_EMAIL environment variable is required.")
if not BOOKING_RECEIVER_EMAIL:
    logger.warning(
        "BOOKING_RECEIVER_EMAIL not set. "
        "Booking notifications will be sent to ADMIN_EMAIL."
    )

logger.info("Gmail SMTP email backend configured")

# --------------------------------------------------
# WhatsApp Configuration (Twilio)
# --------------------------------------------------
# Required environment variables (if WhatsApp enabled):
#   TWILIO_ACCOUNT_SID: Twilio Account SID
#   TWILIO_AUTH_TOKEN: Twilio Auth Token
#   TWILIO_WHATSAPP_FROM: Twilio WhatsApp number (format: whatsapp:+14155238886)
#   WHATSAPP_ADMIN_NUMBER: Admin WhatsApp number (format: whatsapp:+1234567890)
#
# Optional:
#   TWILIO_WHATSAPP_ENABLED: Set to 'true' to enable WhatsApp (default: false)

TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "").strip()
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "").strip()
TWILIO_WHATSAPP_FROM = os.getenv("TWILIO_WHATSAPP_FROM", "").strip()
WHATSAPP_ADMIN_NUMBER = os.getenv("WHATSAPP_ADMIN_NUMBER", "").strip()
TWILIO_WHATSAPP_ENABLED = get_env_bool("TWILIO_WHATSAPP_ENABLED", False)

if TWILIO_WHATSAPP_ENABLED:
    if not all([TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_WHATSAPP_FROM, WHATSAPP_ADMIN_NUMBER]):
        logger.warning(
            "WhatsApp enabled but missing required Twilio credentials. "
            "WhatsApp notifications will be disabled."
        )
        TWILIO_WHATSAPP_ENABLED = False
    else:
        logger.info("Twilio WhatsApp notifications enabled")

# --------------------------------------------------
# Production security (unchanged)
# --------------------------------------------------

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "true").lower() == "true"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True